/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradle;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class AdminUI_sanity {
	public static boolean flag;
	public static WebDriver driver;
	
	
	public static boolean launchBrowser(String Browser)
	{
		if (Browser.equalsIgnoreCase("chrome")) {
			System.setProperty("webdriver.chrome.driver", Constants.chromepath);
			driver = new ChromeDriver();
			driver.manage().window().maximize();
			flag = true;
		}
		
   
		if (Browser.equalsIgnoreCase("firefox")) {
			System.setProperty("webdriver.gecko.driver", Constants.firepath);
			driver = new ChromeDriver();
			driver.manage().window().maximize();
			flag = true;
		}
		return flag;
    }
	

}
